# Generated by Django 6.0 on 2025-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='low_stock_threshold',
            new_name='reorder_level',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
